### PR TITLE
Rebuild with newer gcc

### PR DESCRIPTION
**Pull request by mcflugen**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This pull request is an attempt to rebuild *bmi-fortran* with a newer version of *gcc*/*gfortran*.

### CODE REVIEW

**Comment by mcflugen** [comment]
@conda-forge-admin, please rerender

**Comment by mcflugen** [comment]
@mdpiper What do you think of this? I've been having trouble building projects that use *bmi-fortran* on *LInux* because, I think, it was built with an older version of *gfortran*.

The error I've been getting is something like the following,
```
Fatal Error: Cannot read module file ‘/home/runner/work/babelizer/babelizer/.nox/test-langs-3-10-lang-fortran/include/bmif_2_0.mod’ opened at (1), because it was created by a different version of GNU Fortran
``` 

Anyway, I think this pull request should rebuild it with the latest version.

**Review by mdpiper — APPROVED** [review]

**Comment by mdpiper** [comment]
@mcflugen I've run into this before, and the issue was a mismatch between the compilers and the runtime libraries. I bet I could solve this by improving my conda recipe, but I solved this in the past by installing the compilers and runtime libraries in the same call. Anyway, it's past time for this package to be refreshed. Thank you for working on it.

**Comment by mcflugen** [comment]
@mdpiper Thanks. If you're ok with this, you'll need to merge it.

**Pull request merged**
